# SPDX-FileCopyrightText: 2026 Felix Kästner
# SPDX-License-Identifier: Apache-2.0

version: "2"

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/felix-kaestner/kubectl-secret
